### ISSUE TITLE
Wrong icon for component

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/hydrogen-editions-24#14]
Right-align for column uses the wrong icon (not sure if definition or asset). it functions correctly, just the icon is incorrect. Also, the order is wrong (should be left, center, right, justify)

![Image](https://github.com/concrete-utopia/hydrogen-editions-24/assets/2945037/718e9b8c-d766-4399-989e-41439fe0e908)

**Comment by bkrmendy** [comment]
fixed in https://github.com/concrete-utopia/hydrogen-editions-24/commit/6f4105b4b25593b47d1aeb4a3a45a0efeeead9fe
