### ISSUE TITLE
Add icons to text component controls

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/hydrogen-editions-24#3]
E.g. `Row`, `Column`:

![Image](https://github.com/concrete-utopia/hydrogen-editions-24/assets/127662/0a1bfb65-245f-43d8-8ed1-783f1cb52c28)

**Comment by gbalint** [comment]
Fixed in https://github.com/concrete-utopia/hydrogen-editions-24/pull/9 and https://github.com/concrete-utopia/utopia/pull/5907
