### ISSUE TITLE
Replace all Flex component usages with Row and Column

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/hydrogen-editions-24#4]
We started to replace Flex component with Row and Column, but Flex is still used here and there, let's remove those.

Reasons: 
- we cannot yet dynamically display icons and labels for components, and having "row" vs "column" icons in the sample store is very helpful when navigating layouts
- when composing new layouts (demo flow) it's marginally more intuitive to pick columns and rows - this could be mitigated by annotation changes

Implementation notes: keep props (other than direction) the same

**Comment by gbalint** [comment]
Fixed in https://github.com/concrete-utopia/hydrogen-editions-24/commit/c240444404fc73fa0fa97d15de8cdb448627d830 and https://github.com/concrete-utopia/hydrogen-editions-24/commit/76a023b5bfd87e8589245e23b3826787d434b101
